### PR TITLE
Chore/test empty string 2

### LINKED ISSUE #31: Empty String `""` Code Review Warning Annotation
Annotate them with warnings in code review to more closely scrutinize the logic that interacts with the variable. 

### Rationale
I see a lot of abuse for empty strings. It makes code logic sloppy and more error prone. But since there are some legitimate uses for empty strings, we will just set a warning instead of error?

###### https://github.com/ubiquity/audit.ubq.fi/blob/08fba85a9a592ca2bda5eaeaa2ff3b9fdd4632be/static/scripts/audit-report/audit.ts#L26C1-L27C21

- Should be unset (which implies `undefined`) instead of passing an empty string as a credential or URL. Then the code should check if the value is truthy before expecting authentication.
```typescript
let REPOSITORY_URL;
let GITHUB_PAT;
```

###### https://github.com/ubiquity/ubiquibot-kernel/blame/c553d5a7866c1ef76d4f589d8095c8bb751cbd49/src/github/types/config.ts#L29

- Should be `value.ref ?? "@" + value.ref` as I'm assuming the developer never expected the `""` value to be returned there. 

###### https://github.com/ubiquity/pay.ubq.fi/pull/189/files#r1518549017

- This shouldn't have been here at all. It's not a valid RPC endpoint.

---

### PR DESCRIPTION
**Pull request by 0x4007**
Resolves https://github.com/ubiquity/ts-template/issues/31

Currently matches any instance of `""` but with regex can do more precise targeting (in the future if necessary) i.e. look for `const` or `let` in the same line to identify variable initializations, which is the primary suspect. 

Will leave it looser targeting for now as an open experiment to take note of other specific scenarios to focus on later

### CODE REVIEW

**Comment by 0x4007** [comment]
I got annotations working on the files view but I can't get the line targeting to be accurate.

**Comment by 0x4007** [comment]
Currently matches any instance of `""` but with regex can do more precise targeting (in the future if necessary) i.e. look for `const` or `let` in the same line to identify variable initializations, which is the primary suspect. 

Will leave it looser targeting for now.

**Comment by gentlementlegen** [comment]
@0x4007 It seems you merged this with empty strings: https://github.com/ubiquity/ts-template/actions/runs/11245674853/job/31266132517 could this be fixed?

**Comment by 0x4007** [comment]
It's a warning not an error. This expresses that the reviewers should be cautious and review its context. It should never warn for the same string again because it is designed only to check the pull diff. 

To be fair this probably would work by using `\"\"` but I think this is not a problem anymore to worry about.

**Comment by 0x4007** [comment]
Also I just realized that it doesn't display annotations on GitHub mobile which is extremely unfortunate. At least the CI should clearly indicate a failure.

**Pull request merged**
